In [12]:
import numpy as np 

a = np.arange(12).reshape(3,4)
print(a)
print(a.shape)
print(a.ndim)
print(a.dtype)
print(a.size)
print(a.itemsize)
print(type(a))
b = np.array([10, 20, 30])
print(b)
print(type(b))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)
2
int32
12
4
<class 'numpy.ndarray'>
[10 20 30]
<class 'numpy.ndarray'>


In [14]:
b = np.array([10, 20, 30])
print(b.dtype)

c = np.array([1.3, 4.5, 6.7, 8.9])
print(c.dtype)

int32
float64


In [16]:
d = np.array([(2,4,6), (1,3,5,7)])
print(d)

[(2, 4, 6) (1, 3, 5, 7)]


In [17]:
c = np.array( [ [1,2], [3,4] ], dtype=complex )
print(c)

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


In [18]:
print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [25]:
e = np.array([20,30,40,50])
f = np.arange(4)

g = e-f
print(g)
print(np.sin(g))
print(f < e)

[20 29 38 47]
[ 0.91294525 -0.66363388  0.29636858  0.12357312]
[ True  True  True  True]


In [31]:
A = np.array([[1,2],
              [3,4]])

B = np.array([[5,6],
              [7,8]])

print(A*B)
print(A@B)


[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


In [18]:
# Indexing, Slicing and Iterating
import numpy as np 
from math import pi

C = np.arange(10)**3
print(C, "\n")

print(C[2], "\n")

n = C[: : 2] = 2
print(n, "\n")

print(C, "\n")

m = C[: : -1]
print(list(m), "\n")

D = np.array([2,4,6,8,10])

for i in D:
    print(i**(pi))

[  0   1   8  27  64 125 216 343 512 729] 

8 

2 

[  2   1   2  27   2 125   2 343   2 729] 

[729, 2, 343, 2, 125, 2, 27, 2, 1, 2] 

8.824977827076287
77.8802336483881
278.3775777503137
687.2913351145455
1385.4557313670107


In [21]:
#boolean example --imp- the number of array and names shoule be same

namesArr = np.array(["Umar", "Umair", "Nouroz", "Ali","Umar"])

numArr = np.arange(25).reshape(5,5)

print(numArr , '\n')

print(namesArr , '\n')

print(namesArr == "Umar" , '\n')

print(numArr[namesArr=="Umar"] , '\n')

print(numArr[~(namesArr=="Umar")], '\n')

print(np.unique(namesArr),'\n')

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 

['Umar' 'Umair' 'Nouroz' 'Ali' 'Umar'] 

[ True False False False  True] 

[[ 0  1  2  3  4]
 [20 21 22 23 24]] 

[[ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]] 

['Ali' 'Nouroz' 'Umair' 'Umar'] 



In [54]:
# Multidimensional arrays can have one index per axis. These indices are given in a tuple separated by commas:
import numpy as np 

def function(x,y):
    return 10 * x+y

v = np.fromfunction(function,(4,3), dtype = int)
print(v, "\n")

print(v[3,0], "\n")

print(v[0:4, 2], "\n") # another method for achieving the same result 
# column access ke liye colon nh aega sirf column define krna hai just like note agr colun aya to wo row hojaegi 

print(v[ : , 2], "\n")

print(v[-1], "\n")

print(v[0:4, : ]) # Row access ke liye colon aega 2nd argument mai ke ap kha se kha tk chahte ho numbers 


[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]] 

30 

[ 2 12 22 32] 

[ 2 12 22 32] 

[30 31 32] 

[ 2 12 22 32]


In [77]:
# Shape Manipulation
# Changing the shape of an array

import numpy as np 

y = np.floor(20*np.random.random((3,4)))
print(y, "\n")

print(y.ravel(), "\n")

t = y.reshape(6,2)
print(t, "\n")

print(y.T, "\n")

print(t.T, "\n")

print(t.T.shape, "\n")

print(y.shape, "\n")

print(y)

[[11. 15.  3.  4.]
 [ 2.  1.  1. 18.]
 [ 9. 13.  4.  7.]] 

[11. 15.  3.  4.  2.  1.  1. 18.  9. 13.  4.  7.] 

[[11. 15.]
 [ 3.  4.]
 [ 2.  1.]
 [ 1. 18.]
 [ 9. 13.]
 [ 4.  7.]] 

[[11.  2.  9.]
 [15.  1. 13.]
 [ 3.  1.  4.]
 [ 4. 18.  7.]] 

[[11.  3.  2.  1.  9.  4.]
 [15.  4.  1. 18. 13.  7.]] 

(2, 6) 

(3, 4) 

[[11. 15.  3.  4.]
 [ 2.  1.  1. 18.]
 [ 9. 13.  4.  7.]]


In [91]:
# Stacking together different arrays
import numpy as np 

a = np.floor(10 * np.random.random((2,2)))

b = np.floor(30 * np.random.random((2,2)))

print(a, "\n")

print(b, "\n")

c = np.vstack((a,b)) # row_stack OR vstack 2 method for vertical stack
print(c, "\n")

d = np.column_stack((a,b)) # column_stack OR hstack 2 method for horizontal stack
print(d, "\n")




[[6. 0.]
 [8. 3.]] 

[[21.  9.]
 [24. 11.]] 

[[ 6.  0.]
 [ 8.  3.]
 [21.  9.]
 [24. 11.]] 

[[ 6.  0. 21.  9.]
 [ 8.  3. 24. 11.]] 



In [95]:
import numpy as np 

a = np.arange(12)

b = a 

print(b is a)

b.shape = 3,4

print(a.shape)

True
(3, 4)
